INSERT INTO [dbo].[Products] VALUES(NEWID(), 'The Lord of the Rings: The Fellowship of the Ring', 12.99)
INSERT INTO [dbo].[Products] VALUES(NEWID(), 'To Kill a Mockingbird', 15.99)
INSERT INTO [dbo].[Products] VALUES(NEWID(), 'The Great Gatsby', 5.99)
INSERT INTO [dbo].[Products] VALUES(NEWID(), 'Pride and Prejudice', 21.99)
INSERT INTO [dbo].[Products] VALUES(NEWID(), 'Brave New World', 10.99)

INSERT INTO [dbo].[Products] VALUES(NEWID(), 'The Call of the Wild', 10.99)
INSERT INTO [dbo].[Products] VALUES(NEWID(), 'Moby-Dick', 5.99)
INSERT INTO [dbo].[Products] VALUES(NEWID(), 'The Lion, the Witch and the Wardrobe', 23.29)
INSERT INTO [dbo].[Products] VALUES(NEWID(), 'Frankenstein', 0.99)
INSERT INTO [dbo].[Products] VALUES(NEWID(), 'The Grapes of Wrath', 54.99)